init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: '0.12.4'

cache:
  - "node_modules -> package.json"
  - "%APPDATA%\\npm-cache"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test
