init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: '0.12.4'

cache:
  - node_modules -> package.json
  - "%APPDATA%\\npm-cache"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test

artifacts:
  - path: build\*

deploy:
  - provider: GitHub
    auth_token:
      secure: 5HXfg0QXRwPIx6Hjad37cMQvzBXXGnlX31Wnq+S7gFQw5cR9QV8BlgwWlFfuHuu2
    artifact: build\*
    draft: true
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
